#!/bin/bash
# MSVC 环境设置 + 运行 tauri dev
export VSINSTALLDIR="C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools"
export MSVC_VERSION="14.44.35207"
export WINSDK_VERSION="10.0.26100.0"
export WINKITSDIR="C:/Program Files (x86)/Windows Kits/10"

MSVC_BIN="$VSINSTALLDIR/VC/Tools/MSVC/$MSVC_VERSION/bin/Hostx64/x64"
MSVC_LIB="$VSINSTALLDIR/VC/Tools/MSVC/$MSVC_VERSION/lib/x64"
MSVC_INCLUDE="$VSINSTALLDIR/VC/Tools/MSVC/$MSVC_VERSION/include"
SDK_LIB_UM="$WINKITSDIR/Lib/$WINSDK_VERSION/um/x64"
SDK_LIB_UCRT="$WINKITSDIR/Lib/$WINSDK_VERSION/ucrt/x64"
SDK_INCLUDE_UM="$WINKITSDIR/Include/$WINSDK_VERSION/um"
SDK_INCLUDE_UCRT="$WINKITSDIR/Include/$WINSDK_VERSION/ucrt"
SDK_INCLUDE_SHARED="$WINKITSDIR/Include/$WINSDK_VERSION/shared"
SDK_INCLUDE_WINRT="$WINKITSDIR/Include/$WINSDK_VERSION/winrt"

export LIB="$MSVC_LIB;$SDK_LIB_UM;$SDK_LIB_UCRT"
export INCLUDE="$MSVC_INCLUDE;$SDK_INCLUDE_UM;$SDK_INCLUDE_UCRT;$SDK_INCLUDE_SHARED;$SDK_INCLUDE_WINRT"
export PATH="$MSVC_BIN:$PATH"
export RUSTFLAGS="-C linker=$MSVC_BIN/link.exe"

cd "$(dirname "$0")"
npm run tauri dev
